spring:
  profiles:
    active: dev
  application:
    name: tinyurl

server:
  port: 80

tinyurl:
  checkSign: true
  tsThresholdMillis: 300000
  uidGenType: snowflake
  snowflake:
    dataCenterId: 0
    workerId: 0