FROM registry.docker.com.com/openjdk:8
# MAINTAINER errorfatal89@gmail.com
VOLUME /data
ARG JAR_FILE
#  简化 jar 的名字路径 （#：表示注释掉）
ADD  ./target/${JAR_FILE} tinyurl.jar

#  执行 java -jar 命令 （CMD：在启动容器时才执行此行。RUN：构建镜像时就执行此行）
CMD java -jar -Xms128M -Xmx256M tinyurl.jar

#  设置对外端口为 8080
EXPOSE 8080

